using UnityEngine;

public enum EquipmentSlot
{
    Back,
    Body,
    BodyCloth,
    BodyArmor,
    Hair,
    Head,
    FaceHair,
    RightEyeBack,
    RightEyeFront,
    LeftEyeBack,
    LeftEyeFront,
    Helmet1,
    Helmet2,
    LeftArm,
    LeftArmCloth,
    LeftShoulder,
    LeftWeapon,
    LeftShield,
    RightArm,
    RightArmCloth,
    RightShoulder,
    RightWeapon,
    RightShield,
    LeftFoot,
    LeftFootCloth,
    RightFoot,
    RightFootCloth,
    Cloth,
    Armor,
    Pant,
    Eye
}